# Node公式イメージ
FROM node:24-slim

# 作業ディレクトリの指定
WORKDIR /app

# package.jsonをコピー
COPY ./package.json ./

RUN corepack enable

# Yarn は `/node_modules/.bin` を認識してくれないので PATH に追加
# See: https://github.com/yarnpkg/yarn/issues/1684
ENV PATH=/node_modules/.bin:$PATH

# 依存関係をインストール
# ※イメージにすでにyarnは入ってる
RUN yarn install --modules-folder=/node_modules

EXPOSE 4000